[package]
name = "mqtt-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.24.0"
pretty_env_logger = "0.5"
tokio = {version = "1", features = ["full"]}